config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :categories
  devise_for :users
  root "home#index"
  get "my_page", to: "users#my_page"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items, inverse_of: :item, dependent: :destroy
  belongs_to :category
  has_one_attached :image

  validates :name, :description, :category_id, :buyer_id, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, inverse_of: :order, dependent: :destroy
  belongs_to :seller, class_name: "User", inverse_of: :seller_orders
  belongs_to :buyer, class_name: "User", inverse_of: :buyer_orders
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order, inverse_of: :order_items
  belongs_to :item, inverse_of: :order_items
end

app/models/user.rb
class User < ApplicationRecord
  has_many :buyer_orders, class_name: "Order", foreign_key: :buyer, inverse_of: :buyer, dependent: :destroy
  has_many :seller_orders, class_name: "Order", foreign_key: :seller, inverse_of: :seller, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 25 }

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def new
    @category = Category.new
    @allCat = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully."
      redirect_to my_page_path
    else
      render "new"
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @categories = Category.all
  end

  def create
    @item = Item.new(article_params)
    if @item.save
      order = Order.create(seller_id: current_user.id, buyer_id: @item.buyer_id)
      order_item = OrderItem.create(order_id: order.id, item_id: @item.id)
      flash[:notice] = "Item was created successfully."
      redirect_to my_page_path
    else
      render "new"
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    order_item = OrderItem.where(item_id: @item.id).first
    # order = Order.where(id: order_item.order_id).update(buyer_id: @item.buyer_id)
    # render json: order
    if @item.update(article_params)
      order = Order.where(id: order_item.order_id).update(buyer_id: @item.buyer_id)
      flash[:notice] = "Item was updated successfully."
      redirect_to my_page_path
    else
      render "edit"
    end
  end

  def show
  end

  def destroy
    item = Item.find(params[:id])
    order_item = OrderItem.where(item_id: item.id).first
    order = Order.where(id: order_item.id).first
    item.destroy
    order_item.destroy
    order.destroy
    flash[:notice] = "#{item.name} was successfully removed from your portfolio"
    redirect_to my_page_path
  end

  private

  def article_params
    params.require(:item).permit(:name, :description, :category_id, :buyer_id, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_page
    @users = User.all
    @seller_items = current_user.seller_orders.map { |so| so.order_items.map { |oi| { item: oi.item } } }.flatten
    x = current_user.seller_orders.map { |so| so.order_items.map { |ord| { order: ord.order } } }.flatten
    @buyer = x.map { |z| z[:order].buyer_id }
    @buyer_items = current_user.buyer_orders.map { |bo| bo.order_items.map { |oi| { item: oi.item } } }.flatten
    t = current_user.buyer_orders.map { |bo| bo.order_items.map { |ord| { order: ord.order } } }.flatten
    @seller = t.map { |r| r[:order].seller_id }
    # render json: buyer_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_items_helper.rb
module UserItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<h1 style="padding-top: 50px; padding-bottom: 50px">Add New Category</h1>
<%= render 'shared/errors', obj: @category %>

<h3>Present Categories</h3>

<ul class="list-group list-group-horizontal">
  <% @allCat.each do |cat| %>
    <li class="list-group-item"><%= cat.name %></li>
  <% end %>
</ul>

<%= form_with(model: @category, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name, 'Add Category' %>
    <%= f.text_field :name, autofocus: true, autocomplete: 'Category name', class: 'form-control', placeholder: "Enter New Category" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/home/index.html.erb
<h1 style="padding-top: 50px">Welcome to B-lend Home Page</h1>


<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :item_name, "Item Name" %>
    <%= f.text_field :name, autofocus: true, autocomplete: 'Item name', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
     <%= f.collection_select(:category_id, Category.all, :id, :name,
            { prompt: "Make your selection from the list below"}, { multiple: false, size: 1, class: "custom-select shadow rounded" }) %>
  </div>
    <%= link_to "Add New Category", new_category_path, class: "btn btn-primary" %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, autofocus: true, autocomplete: 'Description', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :buyer_id, "Borrower" %>
     <%= f.collection_select(:buyer_id, User.all.where.not(id: current_user.id), :id, :email,
            { prompt: "Make your selection from the list below"}, { multiple: false, size: 1, class: "custom-select shadow rounded" }) %>
  </div>
  <div class="form-group">
  <% if @item.image.attached? %>
    <%= image_tag(@item.image, style: "width: 200px; display: block") %>
  <% end %>
  <br>
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/items/edit.html.erb
<h1 style="padding-top: 50px; padding-bottom: 50px">Edit Items Page</h1>
<%= render 'shared/errors', obj: @item %>

<%= render 'form' %>

app/views/items/index.html.erb
<h1>This is the Item Index Page</h1>

app/views/items/new.html.erb
<h1 style="padding-top: 50px; padding-bottom: 50px">Add Items Page</h1>
<%= render 'shared/errors', obj: @item %>

<%= render 'form' %>

app/views/layouts/_message.html.erb
<% if alert %>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="alert-heading"><%= alert %></h4>
    </div>
<% end %>
<% if notice %>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="alert-heading"><%= notice %></h4>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <%= link_to "B-Lend", root_path, class: "navbar-brand" %>
        <% if current_user %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item <%= 'active' if request.path == my_page_path %>">
                    <%= link_to "Home", my_page_path, class: "nav-link" %>
                    <%# <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> %>
                </li>
                <li class="nav-item">
                    <%= link_to "Post Item", new_item_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Profile
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                            <%= fa_icon 'edit' %> Edit Profile
                        <% end %>
                        <%# <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a> %>
                    </div>
                </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item user-name">
                        <%= fa_icon 'user' %> <strong><%= current_user.full_name %></strong>
                    </li>
                    <li class="nav-item">
                        <%= link_to("Logout", destroy_user_session_path, class: 'btn btn-danger logout-button', method: :delete) %>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BorrowApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>    
    <div class="container">
      <%= render "layouts/message" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/my_page.html.erb
<h1>My Page</h1>

<div style="padding-top: 50px">
    <h3>Items Lent</h3>
    <% if @seller_items %>
        <table class="table table-hover table-dark">
        <thead>
            <tr>
            <th scope="col">Item #</th>
            <th scope="col">Date</th>
            <th scope="col">Item</th>
            <th scope="col">Description</th>
            <th scope="col">Borrower</th>
            <th scope="col">Photo</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @seller_items.each_with_index do |si, index| %>
                <tr>
                <th class="align-middle" scope="row"><%= "#{index+1}" %></th>
                <td class="align-middle"><%= si[:item].created_at.strftime("%a, %d %b %Y") %></td>
                <td class="align-middle"><%= si[:item].name %></td>
                <td class="align-middle"><%= si[:item].description %></td>
                <% if si[:item].buyer_id %>
                    <td class="align-middle"><%= @users.find(@buyer[index]).email %></td>
                <% end %>
                <td class="align-middle"><%= image_tag(si[:item].image, style: "width: 100px") if si[:item].image.attached? %></td>
                <td class="align-middle"><%= link_to 'Edit', edit_item_path(si[:item]), class: "btn btn-sm btn-warning" %></td>
                <td class="align-middle"><%= link_to 'Delete', item_path(si[:item]), class: "btn btn-sm btn-danger",method: :delete, data: {confirm: "Are you sure?"} %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
    <% end %>
</div>

<div style="padding-top: 50px">
    <h3>Items Borrowed</h3>
    <% if @buyer_items %>
        <table class="table table-hover table-dark">
        <thead>
            <tr>
            <th scope="col">Item #</th>
            <th scope="col">Date</th>
            <th scope="col">Item</th>
            <th scope="col">Description</th>
            <th scope="col">Lender</th>
            <th scope="col">Photo</th>
            </tr>
        </thead>
        <tbody>
            <% @buyer_items.each_with_index do |bi, index| %>
                <tr>
                <th class="align-middle" scope="row"><%= "#{index+1}" %></th>
                <td class="align-middle"><%= bi[:item].created_at.strftime("%a, %d %b %Y") %></td>
                <td class="align-middle"><%= bi[:item].name %></td>
                <td class="align-middle"><%= bi[:item].description %></td>
                <td class="align-middle"><%= @users.find(@seller[index]).email %></td>
                <td class="align-middle"><%= image_tag(bi[:item].image, style: "width: 100px") if bi[:item].image.attached? %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
    <% end %>
</div>